### ISSUE TITLE
[Feat]: user thumbnail and username

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#20]
# Modify User entity

## TODO
- [x] Add default user thumbnail
- [x] add update user thumbnail
- [x] omit user username
