### ISSUE TITLE
[Feat]: Notification 

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#24]
# Notification

## Need discussion
- [ ] How many Noti Channels? 
  - APNS, FCM -> Push
  - Email
  - SMS -> need phone number
  - ETC

## TODO
- [ ] Add device token
- [ ] Add noti module
- [ ] Add noti CRUD
