### ISSUE TITLE
[Feat]: Ingredient Barcode automation

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#25]
# Ingredient Create Barcode automation

## Need discussion
- [ ] What code base, PL? -> nodejs, python, etc..
- [ ] What workflow would be? -> s3 upload and lambda invocation

## TODO
- [ ] Decide what PL
- [ ] Decide what workflow
- [ ] Add Barcode read 
- [ ] Add Barcode info analysis(open api - https://www.data.go.kr/data/15060549/openapi.do)
- [ ] Add Ingredient creation automation(or just create Dto info)
