### ISSUE TITLE
[Feat]: Add in-memory caching

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#38]
## Need discussion

- [x] Add cache storage
- [ ] Add api caching
- [x] Add database cache
- [x] Cache consistency strategy
- [x] How much ttl?

## TODO

- [x] Add cache storage
- [ ] Add api caching
- [x] Add database cache
