### ISSUE TITLE
[Feat]: Python Image Server Deploy

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#42]
## TODO

- [x] add python image processing server cloud run deploy
- [x] add to CI/CD
- [x] add gRPC auth
