### ISSUE TITLE
[BUG]: Node API server build error

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#44]
### Describe the bug

Node API server throws error while webpack build
`@nestjs/micorservice` includes several unused&uninstalled dependency, but webpack try to include those modules.

### Expected behavior

Webpack build success

## TODO
- [x] webpack externals to unused microservice modules
- [x] api docs system division and resetting
- [x] Fix CI/CD
- [x] Remove unusing AWS Lambda deploy setting and CI/CD

**Comment by Istiopaxx** [comment]
fixed on #45
