### ISSUE TITLE
[Feat]: add log tracing feature

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#51]
## TODO

- [ ] change aop decorated function to use npm aop package
- [ ] Add log tracing per request using async storage
- [ ] Add logging to global
