### ISSUE TITLE
[Feat]: Transfer to Spring project

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#58]
## TODO

- [ ] Add project configuration
- [ ] Add user domain
- [ ] Add auth domain
- [ ] Add recipe domain
- [ ] Add ingredient domain
