### ISSUE TITLE
[Feat]: Recipe search

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#62]
## Need Discussion
- What search method? full-text? keyword filtering? 
- On full-text, what tokenizing? Stemming vs N-gram?

## TODO

- [ ] MongoDB Atlas Search setting
- [ ] Add search api
- [ ] Add other filtering get methods

**Comment by Istiopaxx** [comment]
- #73 
From above tests of recipe search features are added, close the issue
