### ISSUE TITLE
[Feat]: Device Tokens and Push Notification

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#65]
## Need discussion

- [ ] Only AOS vs AOS+IOS

## TODO

- [ ] Add Notification entity
- [ ] Add FCM push noti 
- [ ] Add Notification setting
