### ISSUE TITLE
[Feat]: Recent viewed Recipe API

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#66]
## Need discussion

- [ ] View Log Access and usage patterns
- [ ] where to store view logs? Mongodb ? MySQL ? Redis ?
- [ ] How long to store? 1 month ? 1 year ? permanantly ? -> maybe permanantly.. use for recommendation

## TODO

- [ ] View Log entity
- [ ] View Log Get api
