### ISSUE TITLE
[Feat]: Recipe Tag Api

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#67]
## Need discussion

- [ ] How to extract proper tags from automatically scrapped recipe
- [ ] Usage for search api: how much weight would tags take
- [ ] Tags can provide recipe's feature: like high protein or high fiber? kito?
- [ ] Tags can be just string or independent entity?

## TODO

- [ ] Add Recipe Tags to Recipe entity
- [ ] Add search index for tags
