### ISSUE TITLE
Recipe Domain

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#7]
### Need discussion
- [ ] Fix the recipe data structure
- [ ] Recipe access control(private, public)

### TODO
- [ ] Data Schema
- [ ] CRUD
- [ ] Recipe access control(private, public)
- [ ] Add image upload api
- [ ] Recipe step data schema
