### ISSUE TITLE
[Feat]: Add MySQL persistence

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#84]
## Need discussion

- [ ] what orm? maybe prisma/typeorm/sequelize
- [ ] Data modeling -> full normalization

## TODO

- [ ] Add Orm
- [ ] migrate recipe data
