### ISSUE TITLE
[Feat]: recent-viewed recipe API

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#87]
## Need discussion

- [ ] what criteria would be proper of "viewing"? just request recipe detail to api server / spend specific time(e.g. 30 seconds?) in recipe detail page / etc.. 
- [ ] where to store the logs? it should be stored in memory-only or DB? what DB? redis / mongodb / etc..
- [ ] logs should have ttl?

## TODO

- [ ] Add persistence of recipe view log
- [ ] Add caching
- [ ] Add API Endpoint
