### ISSUE TITLE
Ingredient Domain

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#9]
# Ingredient Domain

## Need discussion
- [ ] What ingredient must be add first

## TODO
- [x] CRUD
- [x] Ingredient Enum(meat, vege, fruit, source, etc..)
- [x] Ingredient store Enum(Freezing, Refrigerating, room temperature)
- [ ] Search Expire Date for Ingredients
- [ ] Noti Server pre process

**Comment by Istiopaxx** [comment]
# Need discussion

1. 사용자가 식재료의 보관 방법을 바꾸거나 식재료의 상태를 바꾸었을 때 서비스에 쉽게 반영할 수 있는 방법이 필요함. 
EX) 사용자가 등록할때 실온보관으로 보관하던 식재료를 냉장고에 넣은 경우, 서비스에 하나하나 반영한다는 보장이 없음. UX적으로 보관장소 변경을 쉽게 한다던지(냉장고 화면에서 드래그&드롭으로 보관장소변경?같은 방법) 혹은 다른 방법 필요
<img width="300" alt="스크린샷 2023-03-30 오후 8 03 37" src="https://user-images.githubusercontent.com/38745815/228816695-474047cf-d92d-458e-b705-39e92c470c6d.png">

2. 사용자가 이미 등록해놓은 식재료를 또 등록하려고 할때, 관리의 어려움
EX) 사용자가 이미 달걀을 15구를 사서 냉장고에서 보관하고 있었다. 이때 사용자가 새로운 달걀 15구를 사온다면, 두 달걀은 냉장고 탭에서 다른 객체로 인식되어야 하는가? 현재 디자인은 각 식재료를 따로 등록하므로, 예시의 경우에선 다른 객체로 인식될 것으로 보임. 

3. 사용자가 식재료를 사용했을때, 서비스 반영이 어려움
Ex) 사용자가 달걀을 2개 사용했으면, 일일이 달걀을 사용했다고 서비스에 입력하기 귀찮음. 서비스에서 제공하는 레시피대로 요리를 했다면 레시피 대로 차감하면 되지만, 그냥 달걀 2개를 사용했다면 서비스에 반영하는 방법이 필요. 2번의 경우에서도, 만약 2개의 달걀을 사용했다면 오래된 달걀을 사용했는지 새 달걀을 사용했는지 어떻게 확인하는가?

### Conclusion
식재료 입력 및 관리는 사용자가 일일이 서비스에 식재료 갯수 및 구입, 사용 상태를 보고한다는 보장이 없다는 문제가 있음. 서비스 UX적으로 어떻게 풀어나갈지 논의가 필요함. 
##### 가능한 방안
1. 사용자가 매일 식재료 구입, 사용, 상태변경 등의 결산을 하도록 유도(게이미피케이션, 아님 뭐 다른거)
2. 사용자가 서비스를 사용하면서 큰 액션 없이 구입, 사용, 상태변경 등의 정보를 제공하는 유즈케이스 작성 및 정보 추출 유즈케이스 작성
3. 기타 방안

**Comment by sjsjsj1246** [comment]
일단 기술보다는 UX적으로 해결하도록 합시다
1. 드래그 앤드 드롭으로 재배치 하거나 클릭하면 모달이 띄워져 수정하는 방식으로 보관 방법 수정, 푸쉬 알림으로 주기적으로 관리하도록 유도
2. 구매 일자가 다른 식재료는 서로 다른 식재료로 등록 할 필요 있음. 알림 텍스트를 기재해 알려주도록 함
3. 오래된 달걀을 먼저 사용하는 것은 유저가 자율적으로 해야 할 것임. 우리 서비스를 이용하고 있다면 유통기한이 얼마 남지 않는 식재료가 무엇인지 인지하고 사용하려 할 것임.
