### ISSUE TITLE
[Feat]: Add log level

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#94]
## Need discussion

- [ ] Log level: debug - info - log - warn - error
- [ ] env vars for log level

## TODO

- [ ] Add log level enum
- [ ] Add log level feature for loggers and logging Aop
