### ISSUE TITLE
[Feat]: Improve Recipe Search

### ISSUE THREAD

**Issue by Istiopaxx** [project-refri/refri_be#99]
## Need discussion

- [ ] What search feature should to add?

## TODO

- [ ] Remove low-related results in search results
- [ ] add search in specific properties
